workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build unsigned iOS app bundle
        script: |
          flutter build ios --release --no-codesign
      - name: Create unsigned IPA from app bundle
        script: |
          mkdir -p Payload
          APP_PATH=""
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            APP_PATH="build/ios/iphoneos/Runner.app"
          elif [ -d "build/ios/Release-iphoneos/Runner.app" ]; then
            APP_PATH="build/ios/Release-iphoneos/Runner.app"
          else
            echo "Error: No Runner.app found in expected paths"
            exit 1
          fi
          cp -r "$APP_PATH" Payload/
          echo "Copied app bundle from $APP_PATH"
          if [ "$(ls -A Payload/)" ]; then
            zip -r build/ios/ipa/Runner.ipa Payload/
            echo "IPA created successfully: build/ios/ipa/Runner.ipa"
          else
            echo "Error: Payload still empty after copy"
            exit 1
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app  # Optional: For raw bundle if needed